{% set name = "filetype" %}
{% set version = "1.2.0" %}
{% set sha256 = "66b56cd6474bf41d8c54660347d37afcc3f7d1970648de365c102ef77548aadb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - filetype=filetype.__main__:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - filetype
  source_files:
    - tests
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - filetype --help
    - pytest --ignore="tests/test_benchmark.py"

about:
  home: https://github.com/h2non/filetype.py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Infer file type and MIME type of any file/buffer. No external dependencies.
  description: |
    Small and dependency free Python package to infer file type 
    and MIME type checking the magic numbers signature of a file or buffer.
    This is a Python port from filetype Go package.
  doc_url: https://h2non.github.io/filetype.py/
  dev_url: https://github.com/h2non/filetype.py

extra:
  recipe-maintainers:
    - druvus
