{% set name = "filetype" %}
{% set version = "1.0.13" %}
{% set sha256 = "6a104762fe93d755c962aa96cb3d930a48f91a0761047126c5eead2153e33b03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - filetype=filetype.__main__:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6

test:
  imports:
    - filetype

  commands:
    - filetype --help

about:
  home: https://github.com/h2non/filetype.py
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Infer file type and MIME type of any file/buffer. No external dependencies.
  description: |
    Small and dependency free Python package to infer file type 
    and MIME type checking the magic numbers signature of a file or buffer.
    This is a Python port from filetype Go package.
  doc_url: https://h2non.github.io/filetype.py/
  dev_url: https://github.com/h2non/filetype.py

extra:
  recipe-maintainers:
    - druvus
