travis:
  secure:
    BINSTAR_TOKEN: amqmOQ2MhYBUOzMGXdWRgv7R6nOgm7H/kqjL7D+t11gpb0SvaghRiC+fM/11nmdMBrKoK8Y89jT1aIGnyrGj+SIRKC9u7Vh6vVPpHY8nlLAqNJKnYSaCwxE82Y+UN6YpAYeTGBp08YNpI4fJtMGMw6jqrCeo/Nbej7okO/+YrbS7vOzur8UbfArxzOxomz21YrBY6iuFc2EuG26xsK14pqTcjC4thuUb590ph2GzGd25GJmt9CCtP8pOrc5rCMEkPyv4Goc3JOtyPCRSifEXo2flAK4Q7YGVw52VpXdBh34eOydcUYJfvNQ9HzNWgw5B9qlbZQ9+gSy6aSzyCXdlhvA+UbYoIGmGzFW4zhEd9c547U3gWHl0k+flJD61K2EYXFUlLr5Ze+5z9HfvKWB6XKR17s0J0cmOhvtNHyNWCwdqCrNzHwjLPFm7tKJgnqC76cPC7VswDWAdEUzBYxxutb/LLs6sAJLtUmIDLmyfyWu5BQ01NUb+zPLW9vx9stpnW6yKQjK4cSY0W9uusVHzsYUxHE3lSPzeh9cQgJhZn9sbIGH+2C1fQXnOIpkH2+W72wcQGvSyrosg5s4TF4hYX6ZdJHPhltjsnnIrYaTez9lM1KEtuG92vVyx1kxR7ZW+5iUqRaW7N9GpHKWMigk3UrylgttSfTgXT25IC/HATwQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
