travis:
  secure:
    BINSTAR_TOKEN: iH2bWVoZOQW60fW531stwrD7cqhD78kcgncBx/qZCdlDgSCsXcQHWIjm1+PmvA4Yi+OzpzD9lFI2yDEh0CtIqTHan+CoKs2gaPcmvxu0fikSsdPtHHZPjwu99IZApi82mBLGjYrBP/F6HOoVLGrjT7Lj8s5VDTl1hkIa5PQc+CUhs0Jz8DaMbUgrAK/qbHK1Jp/ROQULcJSW8AhXa6A5IbrFF7dRn8QNwccmUU0T6y4tgxOfprUrA42eegZfDI8OMFsIrAR/pFmle1kAj9B+6VYV3G3t9Nw5xRid5OZrTvaljpOA3COzTWgMTNqj8szvohi66SZDnwB1oVtqmTT62OHu0lv+UPvrj0LTqihre9Ax18ByGQPqwNDWD2gHA1PIGrNMhaMQ11cCHShFvXPeGAQMDQ8ve1JDCqDR3yQ3UtJ5EnfEEsBsCGn4QCh4E+BMpwVoEzcxkgv9puTk/8rdtsOyxpuzrkFZsZ29P97LuX6juGNG2Dpg4WXOhPBwWnK7qnkK5Xy/0D72loK11iW7loJKlxWW+8UccZj1djwpmHzYgCrZtgV9XTb0+ZkmvqdT2irxqcx0dF8EV9X9DbjzxUkSrjoFytGejpaoanSWtbcbmJ6jcIfEDPlnfmSMhDx3JVnn9tS5tPeiR5fBtBd2gfMZXM5ZjFHPh8UkOif3vr0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
